#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
   
    [0] = LAYOUT(
        KC_ESC,   KC_Q,   KC_W,   KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
        KC_LCTRL, KC_A,   KC_S,   KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_MINS, KC_ENT,
        KC_LSHIFT,KC_Z,   KC_X,   KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA,KC_DOT,KC_SLASH,KC_LSHIFT,
        KC_LEFT, KC_RIGHT,KC_LGUI,MO(1), KC_SPC,MO(2),KC_LALT,KC_DOWN,KC_UP
    ),
   [1] = LAYOUT(
        KC_ESC,   KC_Q,   KC_W,   KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
        KC_LCTRL, KC_A,   KC_S,   KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_MINS, KC_ENT,
        KC_LSHIFT,KC_Z,   KC_X,   KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA,KC_DOT,KC_SLASH,KC_LSHIFT,
        KC_LEFT, KC_RIGHT,KC_LGUI,MO(0), KC_SPC,MO(3),KC_LALT,KC_DOWN,KC_UP
    ), 
    [2] = LAYOUT(
        KC_ESC,   KC_Q,   KC_W,   KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
        KC_LCTRL, KC_A,   KC_S,   KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_MINS, KC_ENT,
        KC_LSHIFT,KC_Z,   KC_X,   KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA,KC_DOT,KC_SLASH,KC_LSHIFT,
        KC_LEFT, KC_RIGHT,KC_LGUI,MO(3), KC_SPC,MO(0),KC_LALT,KC_DOWN,KC_UP
    ),
    [3] = LAYOUT(
        KC_ESC,   KC_Q,   KC_W,   KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
        KC_LCTRL, KC_A,   KC_S,   KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_MINS, KC_ENT,
        KC_LSHIFT,KC_Z,   KC_X,   KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA,KC_DOT,KC_SLASH,KC_LSHIFT,
        KC_LEFT, KC_RIGHT,KC_LGUI,MO(0), KC_SPC,MO(0),KC_LALT,KC_DOWN,KC_UP
    )
};
